baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'VVC Website'
theme = 'vitals'
enableRobotsTXT = true

[Params]
    copyright = 'Copyright (c) 2021. All rights reserved.'

    [Params.Hero]
    header = '[Name of University]'
    subheader = 'Veterans Live'
    description = 'Setting the stage for success through conversation.'
    button_text = 'Register now'
    background_img = '/img/hero-background.jpg'

    [Params.Grabber]
    header = 'Join us on the live stream, or watch the recorded talks later'
    details = 'In partnership with Virtual Veterans Communities, [UNIVERSITY NAME] presents a live interview event series, hosted by veterans and military students, all about pursuing higher education.'

    [[Params.Partners]]
    name = 'Virtual Veterans Communities'
    image = '/img/VVTC-logo 3.png'
    [[Params.Partners]]
    name = 'Vets In Tech'
    image = '/img/VetsInTech-logo 3.png'
    [[Params.Partners]]
    name = 'Veterans Affairs'
    image = '/img/VA-logo 3.png'
    [[Params.Partners]]
    name = 'CalVet'
    image = '/img/CalVet_Color_notext 3.png'

    [Params.FeaturedEvent]
    name = 'Featured event'
    details = "Whether you are a current student looking to maximize your benefits, a veteran considering a degree, still actively serving and making plans for your transition, or a military family member looking to upskill — this event will provide you with valuable insight. We’ll walk you through developing goals, creating an action plan, and making decisions to get the most out of the benefits you’ve earned through your service."
    talkingpoints = [
        "TP one",
        "Another talking point"
    ]

    [[Params.FeaturedEvent.speakers]]
    name = 'Brian'
    role = 'Speaker role'
    description = 'Lorem ipsum etc'
    image = '/img/brian.jpg'
    [[Params.FeaturedEvent.speakers]]
    name = 'Jill'
    role = 'Lady speaker'
    description = 'Nisi consequat'
    image = '/img/jill.jpg'
    [[Params.FeaturedEvent.speakers]]
    name = 'Guy'
    role = 'Other speaker'
    description = 'More stuff about stuff'
    image = '/img/guy.jpg'

