baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'VVC Website'
theme = 'vitals'

[Params]
    copyright = 'Copyright (c) 2021. All rights reserved.'

    [Params.Hero]
    header = '[Name of University]'
    subheader = 'Veterans Live'
    description = 'Setting the stage for success through conversation.'
    button_text = 'Register now'
    background_img = '/img/hero-background.jpg'

    [Params.Grabber]
    header = 'Join us on the live stream, or watch the recorded talks later'
    details = 'In partnership with Virtual Veterans Communities, [UNIVERSITY NAME] presents a live interview event series, hosted by veterans and military students, all about pursuing higher education.'

    [[Params.Partners]]
    name = 'Virtual Veterans Communities'
    image = '/img/VVTC-logo 3.png'
    [[Params.Partners]]
    name = 'Vets In Tech'
    image = '/img/VetsInTech-logo 3.png'

